/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BlogYonetRouteImport } from './routes/blog-yonet'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as GizlilikRouteImport } from './routes/gizlilik'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as IlanlarRouteImport } from './routes/ilanlar'
import { Route as IsletmePaneliRouteImport } from './routes/isletme-paneli'
import { Route as IsverenlerRouteImport } from './routes/isverenler'
import { Route as KayitRouteImport } from './routes/kayit'
import { Route as KullanimKosullariRouteImport } from './routes/kullanim-kosullari'
import { Route as NasilCalisirRouteImport } from './routes/nasil-calisir'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SifreYenileRouteImport } from './routes/sifre-yenile'
import { Route as StajyerBulRouteImport } from './routes/stajyer-bul'
import { Route as YonetimRouteImport } from './routes/yonetim'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogYonetRoute = BlogYonetRouteImport.update({
  id: '/blog-yonet',
  path: '/blog-yonet',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikRoute = GizlilikRouteImport.update({
  id: '/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanlarRoute = IlanlarRouteImport.update({
  id: '/ilanlar',
  path: '/ilanlar',
  getParentRoute: () => rootRouteImport,
} as any)
const IsletmePaneliRoute = IsletmePaneliRouteImport.update({
  id: '/isletme-paneli',
  path: '/isletme-paneli',
  getParentRoute: () => rootRouteImport,
} as any)
const IsverenlerRoute = IsverenlerRouteImport.update({
  id: '/isverenler',
  path: '/isverenler',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitRoute = KayitRouteImport.update({
  id: '/kayit',
  path: '/kayit',
  getParentRoute: () => rootRouteImport,
} as any)
const KullanimKosullariRoute = KullanimKosullariRouteImport.update({
  id: '/kullanim-kosullari',
  path: '/kullanim-kosullari',
  getParentRoute: () => rootRouteImport,
} as any)
const NasilCalisirRoute = NasilCalisirRouteImport.update({
  id: '/nasil-calisir',
  path: '/nasil-calisir',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SifreYenileRoute = SifreYenileRouteImport.update({
  id: '/sifre-yenile',
  path: '/sifre-yenile',
  getParentRoute: () => rootRouteImport,
} as any)
const StajyerBulRoute = StajyerBulRouteImport.update({
  id: '/stajyer-bul',
  path: '/stajyer-bul',
  getParentRoute: () => rootRouteImport,
} as any)
const YonetimRoute = YonetimRouteImport.update({
  id: '/yonetim',
  path: '/yonetim',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/blog-yonet': typeof BlogYonetRoute
  '/giris': typeof GirisRoute
  '/gizlilik': typeof GizlilikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/ilanlar': typeof IlanlarRoute
  '/isletme-paneli': typeof IsletmePaneliRoute
  '/isverenler': typeof IsverenlerRoute
  '/kayit': typeof KayitRoute
  '/kullanim-kosullari': typeof KullanimKosullariRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/profil': typeof ProfilRoute
  '/sifre-yenile': typeof SifreYenileRoute
  '/stajyer-bul': typeof StajyerBulRoute
  '/yonetim': typeof YonetimRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/blog-yonet': typeof BlogYonetRoute
  '/giris': typeof GirisRoute
  '/gizlilik': typeof GizlilikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/ilanlar': typeof IlanlarRoute
  '/isletme-paneli': typeof IsletmePaneliRoute
  '/isverenler': typeof IsverenlerRoute
  '/kayit': typeof KayitRoute
  '/kullanim-kosullari': typeof KullanimKosullariRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/profil': typeof ProfilRoute
  '/sifre-yenile': typeof SifreYenileRoute
  '/stajyer-bul': typeof StajyerBulRoute
  '/yonetim': typeof YonetimRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/blog-yonet': typeof BlogYonetRoute
  '/giris': typeof GirisRoute
  '/gizlilik': typeof GizlilikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/ilanlar': typeof IlanlarRoute
  '/isletme-paneli': typeof IsletmePaneliRoute
  '/isverenler': typeof IsverenlerRoute
  '/kayit': typeof KayitRoute
  '/kullanim-kosullari': typeof KullanimKosullariRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/profil': typeof ProfilRoute
  '/sifre-yenile': typeof SifreYenileRoute
  '/stajyer-bul': typeof StajyerBulRoute
  '/yonetim': typeof YonetimRoute
  '/blog_/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/blog-yonet'
    | '/giris'
    | '/gizlilik'
    | '/hakkimizda'
    | '/ilanlar'
    | '/isletme-paneli'
    | '/isverenler'
    | '/kayit'
    | '/kullanim-kosullari'
    | '/nasil-calisir'
    | '/profil'
    | '/sifre-yenile'
    | '/stajyer-bul'
    | '/yonetim'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/blog-yonet'
    | '/giris'
    | '/gizlilik'
    | '/hakkimizda'
    | '/ilanlar'
    | '/isletme-paneli'
    | '/isverenler'
    | '/kayit'
    | '/kullanim-kosullari'
    | '/nasil-calisir'
    | '/profil'
    | '/sifre-yenile'
    | '/stajyer-bul'
    | '/yonetim'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/blog-yonet'
    | '/giris'
    | '/gizlilik'
    | '/hakkimizda'
    | '/ilanlar'
    | '/isletme-paneli'
    | '/isverenler'
    | '/kayit'
    | '/kullanim-kosullari'
    | '/nasil-calisir'
    | '/profil'
    | '/sifre-yenile'
    | '/stajyer-bul'
    | '/yonetim'
    | '/blog_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  BlogYonetRoute: typeof BlogYonetRoute
  GirisRoute: typeof GirisRoute
  GizlilikRoute: typeof GizlilikRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IlanlarRoute: typeof IlanlarRoute
  IsletmePaneliRoute: typeof IsletmePaneliRoute
  IsverenlerRoute: typeof IsverenlerRoute
  KayitRoute: typeof KayitRoute
  KullanimKosullariRoute: typeof KullanimKosullariRoute
  NasilCalisirRoute: typeof NasilCalisirRoute
  ProfilRoute: typeof ProfilRoute
  SifreYenileRoute: typeof SifreYenileRoute
  StajyerBulRoute: typeof StajyerBulRoute
  YonetimRoute: typeof YonetimRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-yonet': {
      id: '/blog-yonet'
      path: '/blog-yonet'
      fullPath: '/blog-yonet'
      preLoaderRoute: typeof BlogYonetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik': {
      id: '/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof GizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilanlar': {
      id: '/ilanlar'
      path: '/ilanlar'
      fullPath: '/ilanlar'
      preLoaderRoute: typeof IlanlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isletme-paneli': {
      id: '/isletme-paneli'
      path: '/isletme-paneli'
      fullPath: '/isletme-paneli'
      preLoaderRoute: typeof IsletmePaneliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isverenler': {
      id: '/isverenler'
      path: '/isverenler'
      fullPath: '/isverenler'
      preLoaderRoute: typeof IsverenlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit': {
      id: '/kayit'
      path: '/kayit'
      fullPath: '/kayit'
      preLoaderRoute: typeof KayitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kullanim-kosullari': {
      id: '/kullanim-kosullari'
      path: '/kullanim-kosullari'
      fullPath: '/kullanim-kosullari'
      preLoaderRoute: typeof KullanimKosullariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasil-calisir': {
      id: '/nasil-calisir'
      path: '/nasil-calisir'
      fullPath: '/nasil-calisir'
      preLoaderRoute: typeof NasilCalisirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sifre-yenile': {
      id: '/sifre-yenile'
      path: '/sifre-yenile'
      fullPath: '/sifre-yenile'
      preLoaderRoute: typeof SifreYenileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stajyer-bul': {
      id: '/stajyer-bul'
      path: '/stajyer-bul'
      fullPath: '/stajyer-bul'
      preLoaderRoute: typeof StajyerBulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yonetim': {
      id: '/yonetim'
      path: '/yonetim'
      fullPath: '/yonetim'
      preLoaderRoute: typeof YonetimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  BlogYonetRoute: BlogYonetRoute,
  GirisRoute: GirisRoute,
  GizlilikRoute: GizlilikRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IlanlarRoute: IlanlarRoute,
  IsletmePaneliRoute: IsletmePaneliRoute,
  IsverenlerRoute: IsverenlerRoute,
  KayitRoute: KayitRoute,
  KullanimKosullariRoute: KullanimKosullariRoute,
  NasilCalisirRoute: NasilCalisirRoute,
  ProfilRoute: ProfilRoute,
  SifreYenileRoute: SifreYenileRoute,
  StajyerBulRoute: StajyerBulRoute,
  YonetimRoute: YonetimRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
