/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as IlanlarRouteImport } from './routes/ilanlar'
import { Route as IsletmePaneliRouteImport } from './routes/isletme-paneli'
import { Route as IsverenlerRouteImport } from './routes/isverenler'
import { Route as KayitRouteImport } from './routes/kayit'
import { Route as NasilCalisirRouteImport } from './routes/nasil-calisir'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as StajyerBulRouteImport } from './routes/stajyer-bul'
import { Route as YonetimRouteImport } from './routes/yonetim'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BlogBlogRouteImport } from './routes/blog.tsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanlarRoute = IlanlarRouteImport.update({
  id: '/ilanlar',
  path: '/ilanlar',
  getParentRoute: () => rootRouteImport,
} as any)
const IsletmePaneliRoute = IsletmePaneliRouteImport.update({
  id: '/isletme-paneli',
  path: '/isletme-paneli',
  getParentRoute: () => rootRouteImport,
} as any)
const IsverenlerRoute = IsverenlerRouteImport.update({
  id: '/isverenler',
  path: '/isverenler',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitRoute = KayitRouteImport.update({
  id: '/kayit',
  path: '/kayit',
  getParentRoute: () => rootRouteImport,
} as any)
const NasilCalisirRoute = NasilCalisirRouteImport.update({
  id: '/nasil-calisir',
  path: '/nasil-calisir',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const StajyerBulRoute = StajyerBulRouteImport.update({
  id: '/stajyer-bul',
  path: '/stajyer-bul',
  getParentRoute: () => rootRouteImport,
} as any)
const YonetimRoute = YonetimRouteImport.update({
  id: '/yonetim',
  path: '/yonetim',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlogRoute = BlogBlogRouteImport.update({
  id: '/blog/blog',
  path: '/blog/blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/ilanlar': typeof IlanlarRoute
  '/isletme-paneli': typeof IsletmePaneliRoute
  '/isverenler': typeof IsverenlerRoute
  '/kayit': typeof KayitRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/profil': typeof ProfilRoute
  '/stajyer-bul': typeof StajyerBulRoute
  '/yonetim': typeof YonetimRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/blog': typeof BlogBlogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/ilanlar': typeof IlanlarRoute
  '/isletme-paneli': typeof IsletmePaneliRoute
  '/isverenler': typeof IsverenlerRoute
  '/kayit': typeof KayitRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/profil': typeof ProfilRoute
  '/stajyer-bul': typeof StajyerBulRoute
  '/yonetim': typeof YonetimRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/blog': typeof BlogBlogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/ilanlar': typeof IlanlarRoute
  '/isletme-paneli': typeof IsletmePaneliRoute
  '/isverenler': typeof IsverenlerRoute
  '/kayit': typeof KayitRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/profil': typeof ProfilRoute
  '/stajyer-bul': typeof StajyerBulRoute
  '/yonetim': typeof YonetimRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/blog': typeof BlogBlogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/giris'
    | '/hakkimizda'
    | '/ilanlar'
    | '/isletme-paneli'
    | '/isverenler'
    | '/kayit'
    | '/nasil-calisir'
    | '/profil'
    | '/stajyer-bul'
    | '/yonetim'
    | '/blog/$slug'
    | '/blog/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/giris'
    | '/hakkimizda'
    | '/ilanlar'
    | '/isletme-paneli'
    | '/isverenler'
    | '/kayit'
    | '/nasil-calisir'
    | '/profil'
    | '/stajyer-bul'
    | '/yonetim'
    | '/blog/$slug'
    | '/blog/blog'
  id:
    | '__root__'
    | '/'
    | '/giris'
    | '/hakkimizda'
    | '/ilanlar'
    | '/isletme-paneli'
    | '/isverenler'
    | '/kayit'
    | '/nasil-calisir'
    | '/profil'
    | '/stajyer-bul'
    | '/yonetim'
    | '/blog/$slug'
    | '/blog/blog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GirisRoute: typeof GirisRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IlanlarRoute: typeof IlanlarRoute
  IsletmePaneliRoute: typeof IsletmePaneliRoute
  IsverenlerRoute: typeof IsverenlerRoute
  KayitRoute: typeof KayitRoute
  NasilCalisirRoute: typeof NasilCalisirRoute
  ProfilRoute: typeof ProfilRoute
  StajyerBulRoute: typeof StajyerBulRoute
  YonetimRoute: typeof YonetimRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogBlogRoute: typeof BlogBlogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilanlar': {
      id: '/ilanlar'
      path: '/ilanlar'
      fullPath: '/ilanlar'
      preLoaderRoute: typeof IlanlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isletme-paneli': {
      id: '/isletme-paneli'
      path: '/isletme-paneli'
      fullPath: '/isletme-paneli'
      preLoaderRoute: typeof IsletmePaneliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isverenler': {
      id: '/isverenler'
      path: '/isverenler'
      fullPath: '/isverenler'
      preLoaderRoute: typeof IsverenlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit': {
      id: '/kayit'
      path: '/kayit'
      fullPath: '/kayit'
      preLoaderRoute: typeof KayitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasil-calisir': {
      id: '/nasil-calisir'
      path: '/nasil-calisir'
      fullPath: '/nasil-calisir'
      preLoaderRoute: typeof NasilCalisirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stajyer-bul': {
      id: '/stajyer-bul'
      path: '/stajyer-bul'
      fullPath: '/stajyer-bul'
      preLoaderRoute: typeof StajyerBulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yonetim': {
      id: '/yonetim'
      path: '/yonetim'
      fullPath: '/yonetim'
      preLoaderRoute: typeof YonetimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/blog': {
      id: '/blog/blog'
      path: '/blog/blog'
      fullPath: '/blog/blog'
      preLoaderRoute: typeof BlogBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GirisRoute: GirisRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IlanlarRoute: IlanlarRoute,
  IsletmePaneliRoute: IsletmePaneliRoute,
  IsverenlerRoute: IsverenlerRoute,
  KayitRoute: KayitRoute,
  NasilCalisirRoute: NasilCalisirRoute,
  ProfilRoute: ProfilRoute,
  StajyerBulRoute: StajyerBulRoute,
  YonetimRoute: YonetimRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogBlogRoute: BlogBlogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
